<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>dbe2a955-f10c-47c6-bcc3-43b50b56693f</groupId>
	<artifactId>inventory-smtp-sys-api</artifactId>
	<version>1.0.1</version>
	<packaging>mule-application</packaging>
	<name>inventory-smtp-sapi</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<mule.maven.plugin.version>4.5.3</mule.maven.plugin.version>
		<munit.version>3.2.1</munit.version>
		<mule-secure-configuration-property-module.version>1.2.7</mule-secure-configuration-property-module.version>
		<assertions.version>1.2.1</assertions.version>
		<http.connector.version>1.10.0</http.connector.version>
		<validation.module.version>2.0.6</validation.module.version>
		<apikit.module.version>1.11.0</apikit.module.version>
		<mule.salesforce.connector.version>10.22.2</mule.salesforce.connector.version>
		<raml.version>1.0.0</raml.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.2.0</version>
			</plugin>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<cloudhub2Deployment>
						<uri>https://anypoint.mulesoft.com</uri>
						<provider>MC</provider>
						<environment>${environment}</environment>
						<target>Cloudhub-US-East-2</target>
						<muleVersion>${muleVersion}</muleVersion>
						<releaseChannel>LTS</releaseChannel>
						<server>anypoint-exchange-v3</server>
						<connectedAppClientId>${CLIENT_ID}</connectedAppClientId>
						<connectedAppClientSecret>${CLIENT_SECRET}</connectedAppClientSecret>
						<connectedAppGrantType>client_credentials</connectedAppGrantType>
						<businessGroupId>${businessGroupId}</businessGroupId>
						<applicationName>inventory-smtp-sapi-${mule.env}</applicationName>
						<javaVersion>17</javaVersion>
						<replicas>${replicas}</replicas>
						<vCores>${vCores}</vCores>
						<integrations>
							<services>
								<objectStoreV2>
									<enabled>true</enabled>
								</objectStoreV2>
							</services>
						</integrations>
						<properties>
							<anypoint.platform.config.analytics.agent.enabled>true</anypoint.platform.config.analytics.agent.enabled>
							<anypoint.platform.visualizer.displayName>${project.artifactId}</anypoint.platform.visualizer.displayName>
							<anypoint.platform.visualizer.layer>System</anypoint.platform.visualizer.layer>
							<mule.env>${mule.env}</mule.env>
						</properties>
						<deploymentSettings>
							<generateDefaultPublicUrl>true</generateDefaultPublicUrl>
						</deploymentSettings>
						<secureProperties>
							<mule.key>${mule.key}</mule.key>
						</secureProperties>
					</cloudhub2Deployment>
					<classifier>mule-application</classifier>
					<sharedLibraries>
						<sharedLibrary>
							<groupId>org.springframework.security</groupId>
							<artifactId>spring-security-config</artifactId>
						</sharedLibrary>
						<sharedLibrary>
							<groupId>org.springframework</groupId>
							<artifactId>spring-core</artifactId>
						</sharedLibrary>
						<sharedLibrary>
							<groupId>org.springframework.security</groupId>
							<artifactId>spring-security-core</artifactId>
						</sharedLibrary>
						<sharedLibrary>
							<groupId>org.springframework.security</groupId>
							<artifactId>spring-security-crypto</artifactId>
						</sharedLibrary>
						<sharedLibrary>
							<groupId>org.springframework</groupId>
							<artifactId>spring-beans</artifactId>
						</sharedLibrary>
						<sharedLibrary>
							<groupId>org.springframework</groupId>
							<artifactId>spring-context</artifactId>
						</sharedLibrary>
					</sharedLibraries>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.mulesoft.munit.tools</groupId>
				<artifactId>munit-maven-plugin</artifactId>
				<version>${munit.version}</version>
				<executions>
					<execution>
						<id>test</id>
						<phase>test</phase>
						<goals>
							<goal>test</goal>
							<goal>coverage-report</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<coverage>
						<runCoverage>true</runCoverage>
						<failBuild>false</failBuild>
						<requiredApplicationCoverage>70</requiredApplicationCoverage>
						<requiredResourceCoverage>70</requiredResourceCoverage>
						<requiredFlowCoverage>70</requiredFlowCoverage>
						<formats>
							<format>console</format>
							<format>html</format>
							<format>json</format>
						</formats>
					</coverage>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-config</artifactId>
			<version>5.8.12</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>5.3.34</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-core</artifactId>
			<version>5.8.12</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-crypto</artifactId>
			<version>5.8.12</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
			<version>5.3.34</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>5.3.34</version>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.modules</groupId>
			<artifactId>mule-secure-configuration-property-module</artifactId>
			<version>${mule-secure-configuration-property-module.version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.weave</groupId>
			<artifactId>assertions</artifactId>
			<version>${assertions.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<version>1.10.3</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-runner</artifactId>
			<version>3.3.0</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<version>1.11.5</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<version>3.3.0</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-email-connector</artifactId>
			<version>1.8.0</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>dbe2a955-f10c-47c6-bcc3-43b50b56693f</groupId>
			<artifactId>inv-smtp-sapi</artifactId>
			<version>1.0.2</version>
			<classifier>raml</classifier>
			<type>zip</type>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<url>https://repository.mulesoft.org/releases/</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>anypoint-exchange-v2</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v2/maven</url>
			<layout>default</layout>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<layout>default</layout>
			<url>https://repository.mulesoft.org/releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
	<distributionManagement>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Corporate Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/organizations/${project.groupId}/maven</url>
			<layout>default</layout>
		</repository>
	</distributionManagement>
</project>
